name: Deploy

on:
  push:
    branches: 
      - master
  pull_request:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    env:
      HOST: ${{ vars.HOST }}
      PORT: ${{ vars.PORT }}      
      DEPLOY_DIRECTORY: apps/ya-token      
      ENV_FILE_PATH: apps/ya-token/.env
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.tag }}      
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to Github Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.REGISTRY_TOKEN }}
      # - name: Deploy
      #   run: |
      #     sudo apt-get install -y rsync ssh
      #     echo "$DEPLOY_SSH_KEY" > deploy_key.pem
      #     chmod 600 deploy_key.pem
      #     ssh -i deploy_key.pem -o StrictHostKeyChecking=no ${{ env.HOST }} -p ${{ env.PORT }} "mkdir -p ${{ env.DEPLOY_DIRECTORY }}"
      #     rsync -avz -e 'ssh -i deploy_key.pem -p ${{ env.PORT }} -o StrictHostKeyChecking=no' --exclude='.git' ./ ${{ env.HOST }}:${{ env.DEPLOY_DIRECTORY }}
      #   env:
      #     DEPLOY_SSH_KEY: ${{ secrets.DEPLOY_SSH_KEY }}    