name: Deploy

on:
  push:
    branches: 
      - master
  pull_request:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    env:
      HOST: ${{ vars.HOST }}
      PORT: ${{ vars.PORT }}
      DEPLOY_DIRECTORY: /mungu/apps/ya-token
      CONFIG_PATH: /mungu/apps/ya-token/config/prod.yaml
      ENV_FILE_PATH: /mungu/apps/ya-token/.env
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.tag }}

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21.4

      - name: Build app
        run: |
          go mod download
          go build -o ya-token ./cmd/ya-token
      
      - name: Deploy
        run: |
          echo $GITHUB_CONTEX
          sudo apt-get install -y ssh rsync
          echo "$DEPLOY_SSH_KEY"
          echo "$DEPLOY_SSH_KEY" > deploy_key
          chmod 600 deploy_key
          ssh -i deploy_key.pem -o StrictHostKeyChecking=no ${{ env.HOST }} -p ${{ env.PORT }} "mkdir -p ${{ env.DEPLOY_DIRECTORY }}"          
        env:
          DEPLOY_SSH_KEY: ${{ secrets.DEPLOY_SSH_KEY }}