name: Deploy

on:
  push:
    branches: 
      - master
  pull_request:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    env:
      HOST: ${{ vars.HOST }}
      PORT: ${{ vars.PORT }}      
      DEPLOY_DIRECTORY: apps/ya-token      
      ENV_FILE_PATH: apps/ya-token/.env
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.tag }}

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21.4

      - name: Build app
        run: |
          go mod download
          go build -o ya-token ./cmd/ya-token
      
      - name: Deploy
        run: |
          sudo apt-get install -y rsync ssh
          echo "$DEPLOY_SSH_KEY" > deploy_key.pem
          chmod 600 deploy_key.pem
          ssh -i deploy_key.pem -o StrictHostKeyChecking=no ${{ env.HOST }} -p ${{ env.PORT }} "mkdir -p ${{ env.DEPLOY_DIRECTORY }}"
          rsync -avz -e 'ssh -i deploy_key.pem -p ${{ env.PORT }} -o StrictHostKeyChecking=no' --exclude='.git' ./ ${{ env.HOST }}:${{ env.DEPLOY_DIRECTORY }}
        env:
          DEPLOY_SSH_KEY: ${{ secrets.DEPLOY_SSH_KEY }}
      
      - name: Create environment
        run: |                
          ssh -i deploy_key.pem -o StrictHostKeyChecking=no ${{ env.HOST }} -p ${{ env.PORT }} "\
          export 'CONFIG_PATH=prod' && \
          export 'HTTP_SERVER_PASSWORD=${{ secrets.HTTP_SERVER_PASSWORD }}' && \
          export 'YANDEX_CLOUD_TOKEN=${{ secrets.YANDEX_CLOUD_TOKEN }}'