name: Deploy

on:
  push:
    branches: 
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
        default: 'latest'

jobs:
  push_to_registry:
    runs-on: ubuntu-latest
    environment: production
    if: ${{ github.event.workflow_run.conclusion != 'failure' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{github.event.commit_id}}
      
      - name: Env variable assignment
        run: echo "image_repository_name=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
      
      - name: Assign version
        run: |
          echo "TAG_NAME=latest" >> $GITHUB_ENV
          if [ "${{ github.event.release.tag_name }}" != "" ]; then
            echo "TAG_NAME=${{ github.event.release.tag_name }}" >> $GITHUB_ENV
          fi;
          if [ "${{ github.event.inputs.version }}" != "" ]; then
            echo "TAG_NAME=${{ github.event.inputs.version }}" >> $GITHUB_ENV
          fi;

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.REGISTRY_TOKEN }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        if: ${{ github.event.inputs.version == '' || github.event.inputs.version == 'latest' }}
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ghcr.io/${{ env.image_repository_name }}:${{ env.TAG_NAME }}

      # - name: Deploy
      #   run: |
      #     sudo apt-get install -y rsync ssh
      #     echo "$DEPLOY_SSH_KEY" > deploy_key.pem
      #     chmod 600 deploy_key.pem
      #     ssh -i deploy_key.pem -o StrictHostKeyChecking=no ${{ env.HOST }} -p ${{ env.PORT }} "mkdir -p ${{ env.DEPLOY_DIRECTORY }}"
      #     rsync -avz -e 'ssh -i deploy_key.pem -p ${{ env.PORT }} -o StrictHostKeyChecking=no' --exclude='.git' ./ ${{ env.HOST }}:${{ env.DEPLOY_DIRECTORY }}
      #   env:
      #     DEPLOY_SSH_KEY: ${{ secrets.DEPLOY_SSH_KEY }}
  deploy_ssh:
    needs: push_to_registry
    runs-on: ubuntu-latest
    environment: production
    env:
      HOST: ${{ vars.HOST }}
      PORT: ${{ vars.PORT }}
      DEPLOY_DIRECTORY: apps/ya-token
      ENV_FILE_PATH: apps/ya-token/.env
    if: ${{ github.event.workflow_run.conclusion != 'failure' }}
    steps:
      - name: Checkout
        if: ${{ github.event.inputs.version == '' || github.event.inputs.version == 'latest' }}
        uses: actions/checkout@v3

      - name: repository name fix and env
        run: |
          echo "image_repository_name=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
          echo "TAG_NAME=latest" >> $GITHUB_ENV
          if [ "${{ github.event.release.tag_name }}" != "" ]; then
            echo "TAG_NAME=${{ github.event.release.tag_name }}" >> $GITHUB_ENV
          fi;
          if [ "${{ github.event.inputs.version }}" != "" ]; then
            echo "TAG_NAME=${{ github.event.inputs.version }}" >> $GITHUB_ENV
          fi;
      
      - name: Deploy
        if: ${{ github.event.inputs.version == '' || github.event.inputs.version == 'latest' }}
        run: |
          sudo apt-get install -y rsync ssh
          echo "$DEPLOY_SSH_KEY" > deploy_key.pem
          chmod 600 deploy_key.pem
          ssh -i deploy_key.pem -o StrictHostKeyChecking=no ${{ env.HOST }} -p ${{ env.PORT }} "mkdir -p ${{ env.DEPLOY_DIRECTORY }}"
          rsync -avz -e 'ssh -i deploy_key.pem -p ${{ env.PORT }} -o StrictHostKeyChecking=no' --exclude='.git' ./ ${{ env.HOST }}:${{ env.DEPLOY_DIRECTORY }}
        env:
          DEPLOY_SSH_KEY: ${{ secrets.DEPLOY_SSH_KEY }}

      - name: Create env file
        if: ${{ github.event.inputs.version == '' || github.event.inputs.version == 'latest' }}
        run: |
          echo "Generating .env file"
          ssh -i deploy_key.pem -o StrictHostKeyChecking=no ${{ env.HOST }} -p ${{ env.PORT }} "\
          rm -f ${{ env.ENV_FILE_PATH }} && \
          touch ${{ env.ENV_FILE_PATH }} && \
          chmod 600 ${{ env.ENV_FILE_PATH }} && \          
          echo 'CONFIG_PATH=prod' >> ${{ env.ENV_FILE_PATH }} && \
          echo 'IMAGE_REPO=${{ env.image_repository_name }}' >> ${{ env.ENV_FILE_PATH }} && \
          echo 'RELEASE_VERSION=${{ env.TAG_NAME }}' >> ${{ env.ENV_FILE_PATH }} && \
          echo 'YANDEX_CLOUD_TOKEN=${{ secrets.YANDEX_CLOUD_TOKEN }}' >> ${{ env.ENV_FILE_PATH }} && \
          echo 'SERVICE_ACCOUNT_PRIVATE_KEY=${{ secrets.SERVICE_ACCOUNT_PRIVATE_KEY }}' >> ${{ env.ENV_FILE_PATH }} && \
          echo 'HTTP_SERVER_PASSWORD=${{ secrets.HTTP_SERVER_PASSWORD }}' >> ${{ env.ENV_FILE_PATH }}"


      - name: remote docker-compose up via ssh
        if: ${{ github.event.inputs.version == '' || github.event.inputs.version == 'latest' }}
        run: |
          ssh -i deploy_key.pem -o StrictHostKeyChecking=no ${{ env.HOST }} -p ${{ env.PORT }}  "\
          echo $APPTOKEN | docker login ghcr.io -u $USERNAME --password-stdin
          docker compose -f ./${{ env.DEPLOY_DIRECTORY }}/docker-compose.prod.yaml pull && \
          docker compose -f ./${{ env.DEPLOY_DIRECTORY }}/docker-compose.prod.yaml up app -d"
        env:
          APPTOKEN: ${{ secrets.REGISTRY_TOKEN }}
          USERNAME: ${{ github.actor }}